using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using DevExpress.XtraBars.Helpers;
using DevExpress.Skins;
using DevExpress.LookAndFeel;
using DevExpress.UserSkins;
using DevExpress.XtraGrid.Views.Grid;
using DevExpress.Utils;
using System.Collections;


namespace GetIdFromSelectedRow
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
            InitSkinGallery();
            InitGrid();

            // This line of code is generated by Data Source Configuration Wizard
            gridControl.DataSource = new GetIdFromSelectedRow.MainDataSourceDataContext().Companies;
        }
        void InitSkinGallery()
        {
            SkinHelper.InitSkinGallery(rgbiSkins, true);
        }
        BindingList<Person> gridDataList = new BindingList<Person>();
        void InitGrid()
        {
            gridDataList.Add(new Person("John", "Smith"));
            gridDataList.Add(new Person("Gabriel", "Smith"));
            gridDataList.Add(new Person("Ashley", "Smith", "some comment"));
            gridDataList.Add(new Person("Adrian", "Smith", "some comment"));
            gridDataList.Add(new Person("Gabriella", "Smith", "some comment"));
            gridControl.DataSource = gridDataList;
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'rDTimeTrackDataSet.Company' table. You can move, or remove it, as needed.
            this.companyTableAdapter.Fill(this.rDTimeTrackDataSet.Company);

        }

        private void gridControl_Click(object sender, EventArgs e)
        {
            //MessageBox.Show(((DXMouseEventArgs)e).Button.ToString());
            //gridControl.MainView.SourceRow;


            //// Create an empty list.
            //ArrayList rows = new ArrayList();
            //// Add the selected rows to the list.
            //for (int i = 0; i < gridView1.SelectedRowsCount; i++)
            //{
            //    if (gridView1.GetSelectedRows()[i] >= 0)
            //    {
            //        rows.Add(gridView1.GetDataRow(gridView1.GetSelectedRows()[i]));
            //        //MessageBox.Show(gridView1.GetDataRow(gridView1.GetSelectedRows()[i]).Field(gridView1.Columns[0]).ToString());
            //        string ID = gridView1.GetFocusedRowCellValue("CompanyID").ToString();
            //        MessageBox.Show(ID);
            //    }

            //}
        }

        private void gridView1_Click(object sender, EventArgs e)
        {
            if (((DXMouseEventArgs)e).Button == System.Windows.Forms.MouseButtons.Right)
            {
                string ID = gridView1.GetFocusedRowCellValue("CompanyID").ToString();

                MessageBox.Show("Button Pressed: " + ((DXMouseEventArgs)e).Button + "\n\n" +
                    "ID: " + ID);
            }
        }

    }
}