<?xml version="1.0" encoding="utf-8"?><Database Name="RDTimeTrack" Class="MainDataSourceDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LEGLFTWR168728\SQLEXPRESS;Initial Catalog=RDTimeTrack;Integrated Security=True" SettingsObjectName="GetIdFromSelectedRow.Properties.Settings" SettingsPropertyName="RDTimeTrackConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Company" Member="Companies">
    <Type Name="Company">
      <Column Name="CompanyID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="VarChar(75) NOT NULL" CanBeNull="false" />
      <Column Name="HistoricalYears" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="RDConsultantId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>